import type { IFormatOption, IModelCatalogItem, IOutputLocationOption, IRecordingDeviceOption } from '../types'

export const FORMAT_OPTIONS: IFormatOption[] = [
  { value: 'md', label: 'Notes', help: 'Clean Markdown transcript', extension: 'md' },
  { value: 'txt', label: 'Text', help: 'Plain text only', extension: 'txt' },
  { value: 'srt', label: 'SRT', help: 'Subtitle file', extension: 'srt' },
  { value: 'vtt', label: 'VTT', help: 'Web captions', extension: 'vtt' },
  { value: 'json', label: 'JSON', help: 'Structured segments', extension: 'json' },
]

export const MEDIA_EXTENSIONS = ['wav', 'mp3', 'm4a', 'aac', 'flac', 'ogg', 'mp4', 'mov', 'mkv', 'webm']
export const MODEL_EXTENSIONS = ['bin', 'gguf']

export const MODEL_CATALOG: IModelCatalogItem[] = [
  {
    id: 'large-v3-turbo',
    name: 'Whisper Large v3 Turbo',
    fileName: 'ggml-large-v3-turbo.bin',
    multilingual: true,
    sizeMb: 1549,
    speed: 'Balanced',
    quality: 'Strong',
    description: 'High-quality multilingual option with practical runtime.',
    recommended: true,
  },
  {
    id: 'large-v3-turbo-q8-0',
    name: 'Whisper Large v3 Turbo Q8',
    fileName: 'ggml-large-v3-turbo-q8_0.bin',
    multilingual: true,
    sizeMb: 834,
    speed: 'Balanced',
    quality: 'Strong',
    description: 'Quantized turbo model with strong quality and lower storage use.',
    recommended: true,
  },
  {
    id: 'large-v3-turbo-q5-0',
    name: 'Whisper Large v3 Turbo Q5',
    fileName: 'ggml-large-v3-turbo-q5_0.bin',
    multilingual: true,
    sizeMb: 547,
    speed: 'Balanced',
    quality: 'Strong',
    description: 'Compact turbo model for practical multilingual transcripts.',
    recommended: true,
  },
  {
    id: 'large-v3',
    name: 'Whisper Large v3',
    fileName: 'ggml-large-v3.bin',
    multilingual: true,
    sizeMb: 2952,
    speed: 'Slow',
    quality: 'Best',
    description: 'Highest quality option for important recordings.',
    recommended: true,
  },
  {
    id: 'large-v3-q5-0',
    name: 'Whisper Large v3 Q5',
    fileName: 'ggml-large-v3-q5_0.bin',
    multilingual: true,
    sizeMb: 1031,
    speed: 'Slow',
    quality: 'Best',
    description: 'Quantized large model with reduced storage footprint.',
    recommended: true,
  },
  {
    id: 'medium',
    name: 'Whisper Medium',
    fileName: 'ggml-medium.bin',
    multilingual: true,
    sizeMb: 1463,
    speed: 'Slower',
    quality: 'Strong',
    description: 'Stronger recognition for longer or noisier recordings.',
  },
  {
    id: 'medium-q8-0',
    name: 'Whisper Medium Q8',
    fileName: 'ggml-medium-q8_0.bin',
    multilingual: true,
    sizeMb: 785,
    speed: 'Slower',
    quality: 'Strong',
    description: 'Quantized medium model with lower storage use.',
  },
  {
    id: 'medium-q5-0',
    name: 'Whisper Medium Q5',
    fileName: 'ggml-medium-q5_0.bin',
    multilingual: true,
    sizeMb: 514,
    speed: 'Slower',
    quality: 'Strong',
    description: 'Compact medium model for balanced accuracy and storage.',
  },
  {
    id: 'small',
    name: 'Whisper Small',
    fileName: 'ggml-small.bin',
    multilingual: true,
    sizeMb: 465,
    speed: 'Balanced',
    quality: 'Better',
    description: 'Better accuracy for meetings and mixed-language audio.',
  },
  {
    id: 'small-q8-0',
    name: 'Whisper Small Q8',
    fileName: 'ggml-small-q8_0.bin',
    multilingual: true,
    sizeMb: 252,
    speed: 'Balanced',
    quality: 'Better',
    description: 'Quantized small model with practical storage use.',
  },
  {
    id: 'small-q5-1',
    name: 'Whisper Small Q5',
    fileName: 'ggml-small-q5_1.bin',
    multilingual: true,
    sizeMb: 181,
    speed: 'Balanced',
    quality: 'Better',
    description: 'Compact small model for everyday mixed-language transcripts.',
  },
  {
    id: 'base',
    name: 'Whisper Base',
    fileName: 'ggml-base.bin',
    multilingual: true,
    sizeMb: 141,
    speed: 'Fast',
    quality: 'Good',
    description: 'Balanced default for everyday transcripts.',
  },
  {
    id: 'base-q8-0',
    name: 'Whisper Base Q8',
    fileName: 'ggml-base-q8_0.bin',
    multilingual: true,
    sizeMb: 78,
    speed: 'Fast',
    quality: 'Good',
    description: 'Quantized base model for quick local drafts.',
  },
  {
    id: 'base-q5-1',
    name: 'Whisper Base Q5',
    fileName: 'ggml-base-q5_1.bin',
    multilingual: true,
    sizeMb: 57,
    speed: 'Fast',
    quality: 'Good',
    description: 'Compact base model for low storage use.',
  },
  {
    id: 'tiny',
    name: 'Whisper Tiny',
    fileName: 'ggml-tiny.bin',
    multilingual: true,
    sizeMb: 74,
    speed: 'Fastest',
    quality: 'Basic',
    description: 'Quick drafts and short notes on slower machines.',
  },
  {
    id: 'tiny-q8-0',
    name: 'Whisper Tiny Q8',
    fileName: 'ggml-tiny-q8_0.bin',
    multilingual: true,
    sizeMb: 42,
    speed: 'Fastest',
    quality: 'Basic',
    description: 'Quantized tiny model for quick rough drafts.',
  },
  {
    id: 'tiny-q5-1',
    name: 'Whisper Tiny Q5',
    fileName: 'ggml-tiny-q5_1.bin',
    multilingual: true,
    sizeMb: 31,
    speed: 'Fastest',
    quality: 'Basic',
    description: 'Smallest multilingual draft model.',
  },
  {
    id: 'large-v2',
    name: 'Whisper Large v2',
    fileName: 'ggml-large-v2.bin',
    multilingual: true,
    sizeMb: 2951,
    speed: 'Slow',
    quality: 'Legacy',
    description: 'Legacy large model for compatibility checks.',
  },
  {
    id: 'large-v2-q8-0',
    name: 'Whisper Large v2 Q8',
    fileName: 'ggml-large-v2-q8_0.bin',
    multilingual: true,
    sizeMb: 1579,
    speed: 'Slow',
    quality: 'Legacy',
    description: 'Quantized legacy large v2 model.',
  },
  {
    id: 'large-v2-q5-0',
    name: 'Whisper Large v2 Q5',
    fileName: 'ggml-large-v2-q5_0.bin',
    multilingual: true,
    sizeMb: 1031,
    speed: 'Slow',
    quality: 'Legacy',
    description: 'Compact legacy large v2 model.',
  },
  {
    id: 'large-v1',
    name: 'Whisper Large v1',
    fileName: 'ggml-large-v1.bin',
    multilingual: true,
    sizeMb: 2951,
    speed: 'Slow',
    quality: 'Legacy',
    description: 'Original large model for compatibility cases.',
  },
  {
    id: 'medium-en',
    name: 'Whisper Medium English',
    fileName: 'ggml-medium.en.bin',
    multilingual: false,
    sizeMb: 1463,
    speed: 'Slower',
    quality: 'English',
    description: 'Strong English-only recognition for longer audio.',
  },
  {
    id: 'medium-en-q8-0',
    name: 'Whisper Medium English Q8',
    fileName: 'ggml-medium.en-q8_0.bin',
    multilingual: false,
    sizeMb: 785,
    speed: 'Slower',
    quality: 'English',
    description: 'Quantized medium English-only model.',
  },
  {
    id: 'medium-en-q5-0',
    name: 'Whisper Medium English Q5',
    fileName: 'ggml-medium.en-q5_0.bin',
    multilingual: false,
    sizeMb: 514,
    speed: 'Slower',
    quality: 'English',
    description: 'Compact medium English-only model.',
  },
  {
    id: 'small-en',
    name: 'Whisper Small English',
    fileName: 'ggml-small.en.bin',
    multilingual: false,
    sizeMb: 465,
    speed: 'Balanced',
    quality: 'English',
    description: 'Better English-only accuracy.',
  },
  {
    id: 'small-en-q8-0',
    name: 'Whisper Small English Q8',
    fileName: 'ggml-small.en-q8_0.bin',
    multilingual: false,
    sizeMb: 252,
    speed: 'Balanced',
    quality: 'English',
    description: 'Quantized small English-only model.',
  },
  {
    id: 'small-en-q5-1',
    name: 'Whisper Small English Q5',
    fileName: 'ggml-small.en-q5_1.bin',
    multilingual: false,
    sizeMb: 181,
    speed: 'Balanced',
    quality: 'English',
    description: 'Compact small English-only model.',
  },
  {
    id: 'base-en',
    name: 'Whisper Base English',
    fileName: 'ggml-base.en.bin',
    multilingual: false,
    sizeMb: 141,
    speed: 'Fast',
    quality: 'English',
    description: 'Everyday English-only transcripts.',
  },
  {
    id: 'base-en-q8-0',
    name: 'Whisper Base English Q8',
    fileName: 'ggml-base.en-q8_0.bin',
    multilingual: false,
    sizeMb: 78,
    speed: 'Fast',
    quality: 'English',
    description: 'Quantized base English-only model.',
  },
  {
    id: 'base-en-q5-1',
    name: 'Whisper Base English Q5',
    fileName: 'ggml-base.en-q5_1.bin',
    multilingual: false,
    sizeMb: 57,
    speed: 'Fast',
    quality: 'English',
    description: 'Compact base English-only model.',
  },
  {
    id: 'tiny-en',
    name: 'Whisper Tiny English',
    fileName: 'ggml-tiny.en.bin',
    multilingual: false,
    sizeMb: 74,
    speed: 'Fastest',
    quality: 'English',
    description: 'Fast English-only drafts.',
  },
  {
    id: 'tiny-en-q8-0',
    name: 'Whisper Tiny English Q8',
    fileName: 'ggml-tiny.en-q8_0.bin',
    multilingual: false,
    sizeMb: 42,
    speed: 'Fastest',
    quality: 'English',
    description: 'Quantized tiny English-only drafts.',
  },
  {
    id: 'tiny-en-q5-1',
    name: 'Whisper Tiny English Q5',
    fileName: 'ggml-tiny.en-q5_1.bin',
    multilingual: false,
    sizeMb: 31,
    speed: 'Fastest',
    quality: 'English',
    description: 'Smallest English-only draft model.',
  },
]

export const RECORDING_DEVICE_OPTIONS: IRecordingDeviceOption[] = [
  { id: 'system-default', label: 'System Default Microphone', status: 'available' },
]

export const OUTPUT_LOCATION_OPTIONS: IOutputLocationOption[] = [
  { id: 'downloads', label: 'Downloads', description: 'Save finished transcript files to Downloads by default.' },
  { id: 'source-folder', label: 'Source Folder', description: 'Save next to the original media file when possible.' },
  { id: 'custom', label: 'Custom Location', description: 'Choose a destination for this transcript.' },
]
